# Generated by Django 4.0.3 on 2022-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.IntegerField(),
        ),
    ]
